.TH "NWS" "1" "September 2015" "v0.2.0" ""
.SH "NAME"
\fBnws\fR \- normalize whitespace
.SH SYNOPSIS
.P
Normalizes whitespace in one of several modes\.
.P
.RS 2
.nf
nws [\-m <mode>] [<text>\.\.\.]
.fi
.RE
.P
\fB<mode>\fP values (treatment of newlines in multi\-line input):
.P
.RS 2
.nf
mp   (default) multi\-paragraph: fold multiple blank lines into one
fp   flattened multi\-paragraph: normalize each paragraph to single line
sp   single\-paragraph: remove all blank lines\.
sl   single\-line: normalize to single output line
.fi
.RE
.P
Alternatively, specify mode values directly as options; e\.g\., \fB\-\-sp\fP in lieu
.br
of \fB\-m sp\fP
.P
Standard options: \fB\-\-help\fP, \fB\-\-man\fP, \fB\-\-version\fP, \fB\-\-home\fP
.SH DESCRIPTION
.P
\fBnws\fP (\fIn\fRormalize \fIw\fRhite\fIs\fRpace) performs whitespace normalization,
.br
offering several modes\.
.P
Input is provided via one or more operands or, in their absence, via stdin\.
.br
To disambiguate operands from options, precede operands with \fB\-\-\fP as a
.br
separate argument\.
.P
Specifying a mode with option \fB\-m\fP applies only to \fImulti\-line\fR input;
.br
all modes behave identically with respect to normalizing a given single
.br
line, namely:
.br
Any run of any mix of spaces and tabs is replaced with a single space
.br
each, except leading and trailing runs, which are discarded\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-m <mode>\fP or \fB\-\-mode <mode>\fP
.br
where \fB<mode>\fP is one of:
.RS 0
.IP \(bu 2
\fBmp\fP, \fBmulti\-para\fP (default)
.br
Runs of blank (all\-whitespace or empty) lines are replaced with 1 empty
.br
line each, resulting in paragraph\-internal newlines getting preserved,
.br
with blank lines at the beginning, between paragraphs, and at the end
.br
getting normalized to a single empty line each\.  
.IP \(bu 2
\fBfp\fP, \fBflat\-para\fP
.br
Like mode \fBmp\fP, except that paragraph\-internal newlines are replaced
.br
with a single space each, resulting in each paragraph becoming a
.br
single line, with 1 empty line between paragraphs\.  
.IP \(bu 2
\fBsp\fP, \fBsingle\-para\fP
.br
Runs of blank (all\-whitespace or empty) lines are discarded, resulting
.br
in a single paragraph of non\-blank lines\.
.IP \(bu 2
\fBsl\fP, \fBsingle\-line\fP
.br
Normalization includes newlines too, so that any run of any mix of
.br
spaces, tabs, and newlines is replaced with a single space each,
.br
resulting in a single, long output line\.

.RE

.RE
.P
You may specify mode values as options directly; e\.g\., \fB\-\-fp\fP or \fB\-\-flat\-para\fP
.br
in lieu of  \fB\-m fp\fP or \fB\-\-mode fp\fP or \fB\-\-mode flat\-para\fP\|\.
.SH STANDARD OPTIONS
.P
All standard options provide information only\.
.RS 0
.IP \(bu 2
\fB\-h, \-\-help\fP
.br
Prints the contents of the synopsis chapter to stdout for quick reference\.
.IP \(bu 2
\fB\-\-man\fP
.br
Displays this manual page, which is a helpful alternative to using \fBman\fP,
.br
if the manual page isn't installed\.
.IP \(bu 2
\fB\-\-version\fP
.br
Prints version information\.
.IP \(bu 2
\fB\-\-home\fP
.br
Opens this utility's home page in the system's default web browser\.

.RE
.SH LICENSE
.P
For license information, bug reports, and more, visit this utility's home page
.br
by running \fBnws \-\-home\fP
.SH EXAMPLES
.P
The examples use ANSI C\-quoted input strings (\fB$'\.\.\.'\fP) for brevity, which
.br
are supported in Bash, Ksh, and Zsh\.
.br
Empty output lines are represented by \fB~\fP\|\.
.P
.RS 2
.nf
# Single\-line input \- no mode needed\.
$ nws $'  one \\t\\t two  three   '
one two three

# Default: multi\-paragraph mode (`\-m mp` or `\-\-mode multi\-para`)
$ nws <<<$'\\n\\n  one\\n two \\n\\n\\n  three\\n\\n'
~
one
two
~
three
~

# Single\-paragraph mode; `\-m sp` is the short equivalent of
# `\-\-mode single\-para`\.
$ nws \-m sp <<<$'\\n\\n  one\\n two \\n\\n\\n  three\\n\\n'
one
two
three

# Flattened\-paragraph mode; note use of shorcut option `\-\-fp` for `\-m fp`\.
nws \-\-fp <<<$'\\n\\n  one\\n two \\n\\n\\n  three\\n\\n'
~
one two
~
three
~

# Single\-line mode
$ nws \-\-sl <<<$'  one two\\n  three '
one two three
.fi
.RE

