.TH "NWS" "1" "September 2017" "v0.3.3" ""
.SH "NAME"
\fBnws\fR \- normalize whitespace
.SH SYNOPSIS
.P
Normalizes whitespace in one of several modes\.
.P
.RS 2
.nf
nws [\-m <mode>] [[\-i[<ext>]] file\.\.\.]

Condensing <mode>s:

All these modes normalize runs of tabs and spaces to a single space  
each and trim leading and trailing runs; they only differ with respect to
how multi\-line input is processed\.

mp   (default) multi\-paragraph: folds multiple blank lines into one
fp   flattened multi\-paragraph: normalizes each paragraph to single line
sp   single\-paragraph: removes all blank lines\.
sl   single\-line: normalizes to single output line

Transliteration <mode>s:

lf     translates line endings to LF\-only (\\n)
crlf   translates line endings to CRLF (\\r\\n)
ascii  translates Unicode whitespace and punctuation to ASCII
.fi
.RE
.P
Alternatively, specify mode values directly as options; e\.g\., \fB\-\-sp\fP in lieu
.br
of \fB\-m sp\fP
.P
Standard options: \fB\-\-help\fP, \fB\-\-man\fP, \fB\-\-version\fP, \fB\-\-home\fP
.SH DESCRIPTION
.P
\fBnws\fP (\fIn\fRormalize \fIw\fRhite\fIs\fRpace) performs whitespace normalization,
.br
offering several modes in two categories:
.RS 0
.IP \(bu 2
whitespace\-condensing modes:
.br
Trims leading and trailing runs of any mix of tabs and spaces and replaces
.br
them with a single space each\. The individual modes differ only with respect to
.br
how multi\-line input is treated\. 
.IP \(bu 2
whitespace\-transliteration modes:
.br
Line endings can be changed to be Windows\- or Unix\-specific, and select
.br
Unicode whitespace and punctuation can be replaced with their closest ASCII
.br
equivalents\.

.RE
.P
Input is provided either from the specified files or via stdin\.
.br
Output is sent to stdout by default\.
.br
To update files in\-place, use the \fB\-i\fP option (in which case there will be no
.br
stdout output)\. 
.SH OPTIONS
.RS 0
.IP \(bu 2
CONDENSING modes: \fB\-m <mode>\fP or \fB\-\-mode <mode>\fP or \fB\-\-<mode>\fP
.br
where \fB<mode>\fP is one of:
.RS 0
.IP \(bu 2
\fBmp\fP, \fBmulti\-para\fP (default)
.br
Runs of blank (all\-whitespace or empty) lines are replaced with 1 empty
.br
line each, resulting in paragraph\-internal newlines getting preserved,
.br
with blank lines at the beginning, between paragraphs, and at the end
.br
getting normalized to a single empty line each\.  
.IP \(bu 2
\fBfp\fP, \fBflat\-para\fP
.br
Like mode \fBmp\fP, except that paragraph\-internal newlines are replaced
.br
with a single space each, resulting in each paragraph becoming a
.br
single line, with 1 empty line between paragraphs\.  
.IP \(bu 2
\fBsp\fP, \fBsingle\-para\fP
.br
Runs of blank (all\-whitespace or empty) lines are discarded, resulting
.br
in a single paragraph of non\-blank lines\.
.IP \(bu 2
\fBsl\fP, \fBsingle\-line\fP
.br
Normalization includes newlines too, so that any run of any mix of
.br
spaces, tabs, and newlines is replaced with a single space each,
.br
resulting in a single, long output line\.

.RE
.IP \(bu 2
TRANSLITERATION modes: \fB\-m <mode>\fP or \fB\-\-mode <mode>\fPor \fB\-\-<mode>\fP
.br
where \fB<mode>\fP is one of:
.RS 0
.IP \(bu 2
\fBlf\fP
.br
Translates Windows\-style CRLF (\\r\\n) line endings to Unix\-style LF (\\n)
.br
line endings\.
.IP \(bu 2
\fBcrlf\fP
.br
Translates Unix\-style LF (\\n) line endings to Windows\-style CRLF (\\r\\n)
.br
line endings\.
.IP \(bu 2
\fBascii\fP, \fBascii\-punctuation\fP
.br
Translates non\-ASCII Unicode whitespace and punctuation to the closest
.br
ASCII equivalents, while leaving other non\-ASCII characters untouched\.
.br
This is helpful for source\-code samples that have been formatted for display
.br
with typographic quotes, em dashes, and the like, which usually makes the
.br
code indigestible to compilers/interpreters\.

.RE
.IP \(bu 2
\fB\-i[<backup\-suffix>]\fP, \fB\-\-in\-place[=<backup\-suffix>]\fP
.br
Updates the specified files \fIin place\fR; that is, the results of the
.br
normalization are written back to the input file, and no stdout output is
.br
produced\. 
If \fB<backup\-suffix>\fP is specified (recommended), a backup copy of each
.br
input file is made first, simply by appending the suffix to the filename\.  

.RE
.SH STANDARD OPTIONS
.P
All standard options provide information only\.
.RS 0
.IP \(bu 2
\fB\-h, \-\-help\fP
.br
Prints the contents of the synopsis chapter to stdout for quick reference\.
.IP \(bu 2
\fB\-\-man\fP
.br
Displays this manual page, which is a helpful alternative to using \fBman\fP,
.br
if the manual page isn't installed\.
.IP \(bu 2
\fB\-\-version\fP
.br
Prints version information\.
.IP \(bu 2
\fB\-\-home\fP
.br
Opens this utility's home page in the system's default web browser\.

.RE
.SH LICENSE
.P
For license information, bug reports, and more, visit this utility's home page
.br
by running \fBnws \-\-home\fP
.SH EXAMPLES
.P
The examples use ANSI C\-quoted input strings (\fB$'\.\.\.'\fP) for brevity, which
.br
are supported in Bash, Ksh, and Zsh\.
.br
Empty output lines are represented by \fB~\fP\|\.
.P
.RS 2
.nf
## CONDENSING EXAMPLES:

# Single\-line input \- no mode needed\.
$ nws <<< $'  one \\t\\t two  three   '
one two three

# Default: multi\-paragraph mode (`\-m mp` or `\-\-mode multi\-para`)
$ nws <<<$'\\n\\n  one\\n two \\n\\n\\n  three\\n\\n'
~
one
two
~
three
~

# Single\-paragraph mode; `\-m sp` is the short equivalent of
# `\-\-mode single\-para`\.
$ nws \-m sp <<<$'\\n\\n  one\\n two \\n\\n\\n  three\\n\\n'
one
two
three

# Flattened\-paragraph mode; note use of shorcut option `\-\-fp` for `\-m fp`\.
nws \-\-fp <<<$'\\n\\n  one\\n two \\n\\n\\n  three\\n\\n'
~
one two
~
three
~

# Single\-line mode
$ nws \-\-sl <<<$'  one two\\n  three '
one two three

## TRANSLITERATION EXAMPLES:

# Converts a CRLF line\-endings file (Windows) to a LF\-only file (Unix)\.
# No output is produced, because the file is updated in\-place; a backup
# of the original file is created with suffix '\.bak'\. 
$ nws \-\-mode lf \-\-in\-place=\.bak from\-windows\.txt

# Converts a LF\-only file (Unix) to a CRLF line\-endings file (Windows)\.
# No output is produced, because the file is updated in\-place; since no
# backup suffix is specified, no backup file is created\.
$ nws \-\-crlf \-i from\-unix\.txt

# Converts select Unicode whitespace and punctuation chars\. to their 
# closest ASCII equivalents and sends the output to a different file\. 
$ nws \-\-ascii unicode\-punct\.txt > ascii\-punct\.txt
.fi
.RE

