#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "$*" >&2; exit 1; }

res=$(nws --lf <<<$'hi\r')
[[ $res == 'hi' ]] || die "Transliteration to \n failed"

res=$(nws --crlf <<<'hi')
[[ $res == $'hi\r' ]] || die "Transliteration to \r\n failed"

res=$(nws --ascii <<<$'hi,\xc2\xa0\xe2\x80\x9cthere\xe2\x80\x9d')
[[ $res == $'hi, "there"' ]] || die "Transliteration to ASCII punctuation failed"

exit 0
